# Generated by Django 2.0.2 on 2018-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='severity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
